# Generated by Django 6.0.3 on 2026-05-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_events_pictures/')),
                ('posted_as', models.CharField(choices=[('News', 'Training Announcement'), ('Events', 'Employee Appreciation')], default='News', max_length=30)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News / Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-upload_time'],
            },
        ),
    ]
