# Generated by Django 6.0.3 on 2026-08-31 09:55

import android.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='Example: 1.0.0', max_length=20)),
                ('version_code', models.PositiveIntegerField(help_text='Example: 1, 2, 3...', unique=True)),
                ('apk', models.FileField(help_text='Upload APK file', upload_to='android_apk/', validators=[android.models.validate_apk])),
                ('apk_size', models.CharField(blank=True, editable=False, max_length=20)),
                ('force_update', models.BooleanField(default=False, help_text='Force users to update.')),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Android App',
                'verbose_name_plural': 'Android Apps',
                'ordering': ['-version_code'],
            },
        ),
    ]
