# Generated by Django 6.0.3 on 2026-05-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_replied_by'),
    ]

    operations = [
    ]
