# Generated by Django 6.0.3 on 2026-05-07 04:21

import accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_multiple_login', models.BooleanField(default=True)),
                ('max_login_sessions', models.PositiveIntegerField(default=3)),
                ('force_single_device_login', models.BooleanField(default=False)),
                ('force_logout_other_sessions', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('login_ip_restriction', models.BooleanField(default=False)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma separated IPs. Example: 127.0.0.1,192.168.1.10', null=True)),
                ('enable_two_factor_auth', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('lock_account_duration_minutes', models.PositiveIntegerField(default=15)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('division', models.CharField(blank=True, max_length=60, null=True)),
                ('department', models.CharField(blank=True, max_length=60, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=60, null=True)),
                ('group', models.CharField(blank=True, max_length=60, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nine_box_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%y/%m/%d/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLogoutDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('timezone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Bot', 'Bot'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=120, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=120, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('login_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True, null=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOGOUT', 'Logout'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed Login'), ('FORCED', 'Forced Logout')], db_index=True, default='ACTIVE', max_length=20)),
                ('login_success', models.BooleanField(default=True)),
                ('failed_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_trusted_device', models.BooleanField(default=False)),
                ('is_new_device', models.BooleanField(default=True)),
                ('suspicious_login', models.BooleanField(default=False)),
                ('multiple_session', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Device Log',
                'verbose_name_plural': 'Login Device Logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user'], name='accounts_lo_user_id_c1bd07_idx'), models.Index(fields=['status'], name='accounts_lo_status_f27ab0_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_e600a9_idx'), models.Index(fields=['login_time'], name='accounts_lo_login_t_53c2ae_idx')],
            },
        ),
    ]
