# Generated by Django 6.0.3 on 2026-05-07 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_course_allocations', to=settings.AUTH_USER_MODEL)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='course.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Allocation',
                'verbose_name_plural': 'Course Allocations',
                'ordering': ['-id'],
                'unique_together': {('employee', 'courses')},
            },
        ),
        migrations.CreateModel(
            name='PendingCourseAllocation',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Course Allocation',
                'verbose_name_plural': 'Pending Course Allocations',
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courseallocations.courseallocation',),
        ),
    ]
