# Generated by Django 6.0.3 on 2026-05-23 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseallocations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingcourseallocation',
            options={'verbose_name': 'Pending Course Allocation', 'verbose_name_plural': 'Pending Course Allocations'},
        ),
        migrations.AlterUniqueTogether(
            name='courseallocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='remarks',
            field=models.TextField(blank=True, help_text='Enter rejection reason or admin remarks.', null=True),
        ),
    ]
